/**
 * Phase 1B Proposal/SOW Delivery Sprint P4 — proposal share-token
 * TypeScript shapes.
 *
 * Mirrors the `public.proposal_share_tokens` table created by
 * migration `0016_proposal_share_tokens.sql`. Tokens are operator-only
 * in this sprint: the raw token string is generated by the application
 * layer, returned to the operator exactly once, and never persisted —
 * the DB stores only `sha256(rawToken)` as `token_hash`.
 *
 * The runtime token-service helpers are shared in-place from
 * `lib/reports/share-token-service.ts` — the helpers (`generateRawShareToken`,
 * `hashShareToken`, `calculateShareTokenExpiry`, `isExpiryWithinPolicy`,
 * `hashRecipientEmail`) are pure Node-crypto wrappers with no
 * report-domain coupling, so importing them directly from the proposal
 * action layer is the smallest safe diff per Sprint P4 § Task 2.
 *
 * Pure module — no React, no DB, no I/O.
 */

export type ProposalShareTokenStatus = "active" | "revoked" | "expired";

export interface ProposalShareToken {
  id: string;
  workspaceId: string;
  engagementId: string;
  proposalId: string;
  snapshotId: string;

  tokenHash: string;
  status: ProposalShareTokenStatus;

  audienceLabel: string | null;
  recipientEmailHash: string | null;

  expiresAt: string;
  createdByUserId: string | null;
  createdByLabel: string | null;
  createdAt: string;

  revokedAt: string | null;
  revokedByUserId: string | null;
  revokeReason: string | null;

  lastAccessedAt: string | null;
  accessCount: number;

  metadata: Record<string, unknown>;
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// DB row shape — exact column names from migration 0016
// ---------------------------------------------------------------------------

export interface DbProposalShareTokenRow {
  id: string;
  workspace_id: string;
  engagement_id: string;
  proposal_id: string;
  snapshot_id: string;
  token_hash: string;
  status: string;
  audience_label: string | null;
  recipient_email_hash: string | null;
  expires_at: string;
  created_by: string | null;
  created_by_label: string | null;
  created_at: string;
  revoked_at: string | null;
  revoked_by: string | null;
  revoke_reason: string | null;
  last_accessed_at: string | null;
  access_count: number;
  metadata: unknown;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// Eligibility evaluator result — consumed by the operator UI to decide
// whether to surface the Generate Proposal Review Link affordance.
// ---------------------------------------------------------------------------

export type ProposalShareEligibilityReasonCode =
  | "snapshot_voided"
  | "snapshot_not_client_proposal_candidate"
  | "snapshot_not_approved"
  | "snapshot_too_old"
  | "commercial_guard_failed"
  | "draft_watermark_set"
  | "group_b_block_violation"
  | "no_included_options"
  | "sow_surface_not_share_eligible";

export interface ProposalShareEligibilityReason {
  code: ProposalShareEligibilityReasonCode;
  operatorFacingNote: string;
}

export interface ProposalShareEligibility {
  eligible: boolean;
  reasons: ProposalShareEligibilityReason[];
  /**
   * Echoed back so the caller can show the operator the timestamp the
   * evaluator measured "snapshot age" against without re-reading the
   * row.
   */
  evaluatedAt: string;
}

// ---------------------------------------------------------------------------
// Policy constants — Sprint P4 inherits the canon's 14-day default /
// 30-day max from the report side. Exported so the action + UI share
// one source of truth.
// ---------------------------------------------------------------------------

/** Default expiry window for newly-minted proposal share tokens. */
export const DEFAULT_PROPOSAL_SHARE_TOKEN_EXPIRY_DAYS = 14;
/** Hard maximum expiry window per docs/24 canon. */
export const MAX_PROPOSAL_SHARE_TOKEN_EXPIRY_DAYS = 30;
/** Snapshot age threshold for share eligibility (matches report-side default). */
export const MAX_PROPOSAL_SNAPSHOT_AGE_DAYS_FOR_SHARE = 14;
