/**
 * Phase 1B Sprint 4D-B — report share-token TypeScript shapes.
 *
 * Mirrors the `public.report_share_tokens` table created by
 * migration `0014_report_share_tokens.sql`. Tokens are operator-only
 * in this sprint: the raw token string is generated by the application
 * layer, returned to the operator exactly once, and never persisted —
 * the DB stores only `sha256(rawToken)` as `token_hash`.
 *
 * Pure module — no React, no DB, no I/O.
 */

export type ReportShareTokenStatus = "active" | "revoked" | "expired";

export interface ReportShareToken {
  id: string;
  workspaceId: string;
  engagementId: string;
  reportId: string;
  snapshotId: string;

  tokenHash: string;
  status: ReportShareTokenStatus;

  audienceLabel: string | null;
  recipientEmailHash: string | null;

  expiresAt: string;
  createdByUserId: string | null;
  createdByLabel: string | null;
  createdAt: string;

  revokedAt: string | null;
  revokedByUserId: string | null;
  revokeReason: string | null;

  lastAccessedAt: string | null;
  accessCount: number;

  metadata: Record<string, unknown>;
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// DB row shape — exact column names from migration 0014
// ---------------------------------------------------------------------------

export interface DbReportShareTokenRow {
  id: string;
  workspace_id: string;
  engagement_id: string;
  report_id: string;
  snapshot_id: string;
  token_hash: string;
  status: string;
  audience_label: string | null;
  recipient_email_hash: string | null;
  expires_at: string;
  created_by: string | null;
  created_by_label: string | null;
  created_at: string;
  revoked_at: string | null;
  revoked_by: string | null;
  revoke_reason: string | null;
  last_accessed_at: string | null;
  access_count: number;
  metadata: unknown;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// Eligibility evaluator result — consumed by the operator UI to decide
// whether to surface the Generate Share Link affordance.
// ---------------------------------------------------------------------------

export type ReportShareEligibilityReasonCode =
  | "snapshot_voided"
  | "snapshot_not_client_pdf_candidate"
  | "snapshot_not_generated"
  | "snapshot_too_old"
  | "claim_guard_failed"
  | "draft_watermark_set"
  | "group_b_block_violation";

export interface ReportShareEligibilityReason {
  code: ReportShareEligibilityReasonCode;
  operatorFacingNote: string;
}

export interface ReportShareEligibility {
  eligible: boolean;
  reasons: ReportShareEligibilityReason[];
  /**
   * Echoed back so the caller can show the operator the timestamp the
   * evaluator measured "snapshot age" against without re-reading the
   * row.
   */
  evaluatedAt: string;
}

// ---------------------------------------------------------------------------
// Token-service constants — exported so callers (action, eligibility) can
// share them. Token-service helpers are the source of truth for behaviour.
// ---------------------------------------------------------------------------

/** Default expiry window for newly-minted share tokens. */
export const DEFAULT_SHARE_TOKEN_EXPIRY_DAYS = 14;
/** Hard maximum expiry window per docs/22 canon. */
export const MAX_SHARE_TOKEN_EXPIRY_DAYS = 30;
/** Snapshot age threshold for share eligibility. */
export const MAX_SNAPSHOT_AGE_DAYS_FOR_SHARE = 14;
