import type { IntakeRecord } from "./types";

const HELIO: IntakeRecord = {
  engagementId: "helio-aios-q2",
  stakeholders: [
    {
      id: "helio-mira",
      name: "Mira Reyes",
      title: "VP Operations",
      role: "operations",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "1 hour ago",
      summary:
        "Most painful workflows are reconciliation across patient intake, billing, and reporting tools, and long-form clinical documentation review. Has executive sponsorship for a focused first sprint.",
      keySignals: [
        "Three-system reconciliation runs weekly with manual exception handling.",
        "Internal AI working group meets bi-weekly — useful change-management entry point.",
        "CFO has approved an investment band consistent with an Opportunity Sprint.",
      ],
      openQuestions: [
        "Which reconciliation exceptions are policy-bounded vs. judgment calls?",
      ],
      riskFlags: [],
    },
    {
      id: "helio-daniel",
      name: "Daniel Patel",
      title: "Chief Technology Officer",
      role: "it",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "Yesterday",
      summary:
        "Core stack is workable: Salesforce, Athena, NetSuite, and a homegrown ops tool. Data sensitivity policy is documented and enforced.",
      keySignals: [
        "Identity and access controls already documented for AI use cases.",
        "Workflows leak between Salesforce and the homegrown ops tool — integration is the obvious surface.",
      ],
      openQuestions: [
        "Is the homegrown tool a candidate for replacement or augmentation?",
      ],
      riskFlags: [
        "Client-confidential data is in scope; sprint must include explicit governance treatment.",
      ],
    },
    {
      id: "helio-linh",
      name: "Linh Tran",
      title: "Marketing Director",
      role: "marketing",
      status: "completed",
      completionPercent: 100,
      responseQuality: "adequate",
      lastActivity: "Yesterday",
      summary:
        "Marketing is mostly self-sufficient; the cross-team friction is in the handoff from marketing-qualified leads to clinical sales.",
      keySignals: [
        "Marketing-to-sales handoff loses context on clinical fit.",
      ],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "helio-karim",
      name: "Karim Hassan",
      title: "QA Lead",
      role: "operations",
      status: "completed",
      completionPercent: 100,
      responseQuality: "adequate",
      lastActivity: "2 days ago",
      summary:
        "QA workflows include manual chart audits and a monthly compliance pass. Pattern-checking with explicit rules is a credible AI surface.",
      keySignals: [
        "Monthly compliance review is highly repetitive.",
      ],
      openQuestions: [
        "Are the compliance rules versioned in a single place, or distributed across teams?",
      ],
      riskFlags: [],
    },
    {
      id: "helio-avery",
      name: "Avery Chen",
      title: "Sales Director",
      role: "sales",
      status: "completed",
      completionPercent: 100,
      responseQuality: "adequate",
      lastActivity: "2 days ago",
      summary:
        "Sales follow-up is manual but most reps have a personal cadence. The pain is the post-sale handoff into operations.",
      keySignals: [
        "Post-sale handoff into operations is the cross-team friction.",
      ],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "helio-sora",
      name: "Sora Tanaka",
      title: "Customer Success Lead",
      role: "customer-success",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "3 days ago",
      summary:
        "Owns the renewal motion. Repetitive review of patient feedback documentation is the most obvious AI candidate in this org.",
      keySignals: [
        "Patient-feedback review is repeatable and high-volume.",
        "Customer success owns the renewal model — strong expansion motion if first sprint lands.",
      ],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "helio-pat",
      name: "Pat Briggs",
      title: "Frontline Supervisor",
      role: "frontline",
      status: "needs-follow-up",
      completionPercent: 35,
      responseQuality: "thin",
      lastActivity: "5 days ago",
      summary:
        "Started the intake but stopped after section 2. Frontline perspective is critical for understanding workflow friction at the point of work.",
      keySignals: [],
      openQuestions: [
        "What does the actual day-to-day look like during peak intake hours?",
      ],
      riskFlags: [
        "Without frontline coverage, recommendations risk being theoretical.",
      ],
    },
    {
      id: "helio-renee",
      name: "Renee Walsh",
      title: "Finance Director",
      role: "finance",
      status: "not-started",
      completionPercent: 0,
      responseQuality: "missing",
      lastActivity: "—",
      summary:
        "Invited 5 days ago. No activity yet. Finance perspective shapes the budget and ROI framing of the first AI investment.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [
        "Finance perspective is needed to shape the proposal's pricing assumptions.",
      ],
    },
  ],
  roleCoverage: [
    {
      role: "executive",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "VP Operations is the named executive sponsor.",
    },
    {
      role: "operations",
      required: true,
      status: "covered",
      stakeholderCount: 2,
      coverageNote: "VP Operations + QA Lead provide a strong operations read.",
    },
    {
      role: "sales",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Sales Director engaged.",
    },
    {
      role: "marketing",
      required: false,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Marketing Director provided cross-team context.",
    },
    {
      role: "it",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "CTO provided a strong systems read.",
    },
    {
      role: "customer-success",
      required: false,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Customer Success Lead engaged.",
    },
    {
      role: "frontline",
      required: true,
      status: "partial",
      stakeholderCount: 1,
      coverageNote:
        "Frontline supervisor stalled at section 2. Needs personal follow-up.",
    },
    {
      role: "finance",
      required: true,
      status: "missing",
      stakeholderCount: 0,
      coverageNote: "Finance Director invited but not started.",
    },
  ],
  supportingInputs: [
    {
      id: "helio-doc-recon",
      title: "Patient intake reconciliation export (Q1)",
      type: "data-export",
      source: "Daniel Patel · CTO",
      status: "received",
      evidenceQuality: "strong",
      linkedStakeholder: "helio-daniel",
      linkedRole: "it",
      summary:
        "Three-system reconciliation export with exception tagging. Useful for sizing the first automation surface.",
    },
    {
      id: "helio-doc-process",
      title: "Operations workflow map (current state)",
      type: "process-map",
      source: "Mira Reyes · VP Operations",
      status: "received",
      evidenceQuality: "adequate",
      linkedStakeholder: "helio-mira",
      linkedRole: "operations",
      summary:
        "Hand-drawn workflow map. Captures the cross-team handoffs but not the per-step time costs.",
    },
    {
      id: "helio-doc-policy",
      title: "Data governance & access policy",
      type: "policy-doc",
      source: "Daniel Patel · CTO",
      status: "received",
      evidenceQuality: "strong",
      linkedStakeholder: "helio-daniel",
      linkedRole: "it",
      summary:
        "Identity and access controls are documented. Compatible with a scoped AI rollout.",
    },
    {
      id: "helio-doc-qa",
      title: "Monthly compliance review checklist",
      type: "operations-doc",
      source: "Karim Hassan · QA Lead",
      status: "reviewed",
      evidenceQuality: "adequate",
      linkedStakeholder: "helio-karim",
      linkedRole: "operations",
      summary: "30-item checklist used during the monthly compliance pass.",
    },
    {
      id: "helio-doc-finance",
      title: "FY budget & investment thresholds",
      type: "report",
      source: "Renee Walsh · Finance",
      status: "missing",
      evidenceQuality: "unverified",
      linkedStakeholder: "helio-renee",
      linkedRole: "finance",
      summary:
        "Finance has not yet shared the budget context that would shape the proposal's investment band.",
    },
    {
      id: "helio-doc-frontline",
      title: "Frontline shift notes (sample week)",
      type: "operations-doc",
      source: "Pat Briggs · Frontline Supervisor",
      status: "missing",
      evidenceQuality: "unverified",
      linkedStakeholder: "helio-pat",
      linkedRole: "frontline",
      summary:
        "Frontline shift notes still outstanding; required to ground recommendations in real day-to-day work.",
    },
  ],
  followUps: [
    {
      id: "helio-fu-pat",
      label: "Personal nudge to Pat Briggs",
      detail:
        "Frontline supervisor stalled at section 2. A 10-minute call would likely close the loop.",
      target: "Pat Briggs · Frontline Supervisor",
      severity: "high",
    },
    {
      id: "helio-fu-renee",
      label: "Finance kickoff call with Renee Walsh",
      detail:
        "Finance perspective drives the proposal's investment framing — book a 20-minute intro this week.",
      target: "Renee Walsh · Finance Director",
      severity: "high",
    },
    {
      id: "helio-fu-finance-doc",
      label: "Request FY budget context from Finance",
      detail:
        "Sprint cannot finalize the proposal without Finance's investment thresholds.",
      target: "Renee Walsh · Finance Director",
      severity: "medium",
    },
  ],
  intakeRiskNotes: [
    "Frontline + Finance roles still uncovered — these shape both recommendations and proposal framing.",
    "Client-confidential data is in scope. Sprint scope must include explicit governance and human-in-the-loop review.",
  ],
};

const MERIDIAN: IntakeRecord = {
  engagementId: "meridian-aios-q2",
  stakeholders: [
    {
      id: "meridian-tessa",
      name: "Tessa Brandt",
      title: "Managing Partner",
      role: "executive",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "Yesterday",
      summary:
        "Strategic intent is to free up partner-level time. Wants AI focused on document review and synthesis.",
      keySignals: [
        "Partner time is the constrained resource.",
      ],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "meridian-mark",
      name: "Mark Ollier",
      title: "COO",
      role: "operations",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "2 days ago",
      summary:
        "Owns delivery operations across three practice lines. Workflow handoffs between practice lead and operations are the friction.",
      keySignals: [
        "Delivery handoff between practice and operations is repeatable and constrained.",
      ],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "meridian-isla",
      name: "Isla Henrik",
      title: "Practice Lead · Strategy",
      role: "operations",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "2 days ago",
      summary:
        "Strategy work is research-heavy. Document synthesis is a clear AI surface.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "meridian-ravi",
      name: "Ravi Subramaniam",
      title: "IT Lead",
      role: "it",
      status: "completed",
      completionPercent: 100,
      responseQuality: "adequate",
      lastActivity: "3 days ago",
      summary:
        "Stack is mostly Microsoft 365 + a custom case-management tool. Integration readiness is reasonable.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "meridian-julia",
      name: "Julia Crane",
      title: "Marketing Lead",
      role: "marketing",
      status: "completed",
      completionPercent: 100,
      responseQuality: "adequate",
      lastActivity: "3 days ago",
      summary:
        "Marketing operates on a quarterly content cadence; AI-assisted drafting is already ad hoc.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "meridian-sami",
      name: "Sami Okonkwo",
      title: "Senior Associate",
      role: "frontline",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "4 days ago",
      summary:
        "Day-to-day perspective on document research, synthesis, and review.",
      keySignals: [
        "Long-form review is the single biggest time sink.",
      ],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "meridian-erika",
      name: "Erika Lawson",
      title: "Office Manager · Finance",
      role: "finance",
      status: "completed",
      completionPercent: 100,
      responseQuality: "adequate",
      lastActivity: "5 days ago",
      summary:
        "Finance is largely outsourced. Investment posture is supportive of a paid sprint.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
  ],
  roleCoverage: [
    {
      role: "executive",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Managing Partner engaged.",
    },
    {
      role: "operations",
      required: true,
      status: "covered",
      stakeholderCount: 2,
      coverageNote: "COO + Practice Lead provide a strong operations read.",
    },
    {
      role: "sales",
      required: false,
      status: "covered",
      stakeholderCount: 0,
      coverageNote: "Practice leads own sales. Coverage is implicit.",
    },
    {
      role: "marketing",
      required: false,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Marketing Lead engaged.",
    },
    {
      role: "it",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "IT Lead provided systems context.",
    },
    {
      role: "frontline",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Senior Associate provided day-to-day perspective.",
    },
    {
      role: "finance",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Office Manager covers finance posture.",
    },
  ],
  supportingInputs: [
    {
      id: "meridian-doc-cases",
      title: "Case-management workflow export",
      type: "data-export",
      source: "Ravi Subramaniam · IT",
      status: "reviewed",
      evidenceQuality: "strong",
      linkedRole: "it",
      summary: "Two quarters of case-management activity. Strong evidence for synthesis.",
    },
    {
      id: "meridian-doc-process",
      title: "Practice delivery handoff playbook",
      type: "process-map",
      source: "Isla Henrik · Practice Lead",
      status: "reviewed",
      evidenceQuality: "strong",
      linkedRole: "operations",
      summary: "Documented handoff between practice and operations.",
    },
    {
      id: "meridian-doc-research",
      title: "Sample research outputs (anonymized)",
      type: "report",
      source: "Sami Okonkwo · Senior Associate",
      status: "reviewed",
      evidenceQuality: "strong",
      linkedRole: "frontline",
      summary:
        "Three sample research outputs to anchor document synthesis recommendations.",
    },
  ],
  followUps: [],
  intakeRiskNotes: [
    "Two findings rely on a single-source response. Flag for additional evidence before approval.",
  ],
};

const ATLAS: IntakeRecord = {
  engagementId: "atlas-aios-q2",
  stakeholders: [
    {
      id: "atlas-priya",
      name: "Priya Sahni",
      title: "COO",
      role: "executive",
      status: "invited",
      completionPercent: 0,
      responseQuality: "missing",
      lastActivity: "—",
      summary:
        "Invitation queued for tomorrow's batch. COO is the named buyer; expect a strong response once intake opens.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "atlas-vp-ops",
      name: "—",
      title: "VP Operations",
      role: "operations",
      status: "invited",
      completionPercent: 0,
      responseQuality: "missing",
      lastActivity: "—",
      summary: "Stakeholder placeholder; name to be confirmed by COO.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "atlas-qa",
      name: "—",
      title: "QA Lead",
      role: "operations",
      status: "invited",
      completionPercent: 0,
      responseQuality: "missing",
      lastActivity: "—",
      summary: "Stakeholder placeholder; QA workflows are a likely first-sprint surface.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "atlas-it",
      name: "—",
      title: "IT · Systems",
      role: "it",
      status: "invited",
      completionPercent: 0,
      responseQuality: "missing",
      lastActivity: "—",
      summary: "Stakeholder placeholder; integration readiness will shape the sprint plan.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "atlas-frontline",
      name: "—",
      title: "Frontline Supervisor",
      role: "frontline",
      status: "invited",
      completionPercent: 0,
      responseQuality: "missing",
      lastActivity: "—",
      summary: "Frontline perspective is required before recommendations land.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
  ],
  roleCoverage: [
    {
      role: "executive",
      required: true,
      status: "missing",
      stakeholderCount: 0,
      coverageNote: "COO invited but intake not yet open.",
    },
    {
      role: "operations",
      required: true,
      status: "missing",
      stakeholderCount: 0,
      coverageNote: "VP Operations + QA Lead invited.",
    },
    {
      role: "it",
      required: true,
      status: "missing",
      stakeholderCount: 0,
      coverageNote: "IT lead invited.",
    },
    {
      role: "frontline",
      required: true,
      status: "missing",
      stakeholderCount: 0,
      coverageNote: "Frontline Supervisor invited.",
    },
    {
      role: "finance",
      required: false,
      status: "missing",
      stakeholderCount: 0,
      coverageNote: "Finance not yet identified — confirm with COO.",
    },
  ],
  supportingInputs: [],
  followUps: [
    {
      id: "atlas-fu-send",
      label: "Send role-based intake to all 5 stakeholders",
      detail: "Stakeholder list is locked. Target a 7-day intake close.",
      target: "All five stakeholders",
      severity: "high",
    },
    {
      id: "atlas-fu-coo-call",
      label: "Confirm Finance stakeholder with COO",
      detail:
        "Finance role is currently unassigned. COO needs to nominate the Finance contact before kickoff.",
      target: "Priya Sahni · COO",
      severity: "medium",
    },
  ],
  intakeRiskNotes: [
    "Industry compliance requirements need explicit governance treatment in sprint scope.",
    "COO availability for the 30-min intake intro is on the critical path.",
  ],
};

const QUANTA: IntakeRecord = {
  engagementId: "quanta-aios-q1",
  stakeholders: [
    {
      id: "quanta-noah",
      name: "Noah Sterling",
      title: "Chief Operating Officer",
      role: "executive",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "Two weeks ago",
      summary: "Sponsored the engagement; framed throughput as the lead constraint.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "quanta-elena",
      name: "Elena Vargas",
      title: "VP Operations",
      role: "operations",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "Two weeks ago",
      summary: "Owns the operations stack; provided process maps and exception data.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "quanta-ben",
      name: "Ben Asare",
      title: "Sales Director",
      role: "sales",
      status: "completed",
      completionPercent: 100,
      responseQuality: "adequate",
      lastActivity: "Two weeks ago",
      summary: "Cross-functional handoff into operations is the lead pain.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "quanta-marian",
      name: "Marian Holloway",
      title: "Marketing Director",
      role: "marketing",
      status: "completed",
      completionPercent: 100,
      responseQuality: "adequate",
      lastActivity: "Two weeks ago",
      summary: "Marketing-to-operations handoff parallels the sales-to-ops handoff.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "quanta-finance",
      name: "Greg Tanaka",
      title: "Finance Director",
      role: "finance",
      status: "completed",
      completionPercent: 100,
      responseQuality: "adequate",
      lastActivity: "Two weeks ago",
      summary: "Confirmed the investment band and procurement timeline.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "quanta-it",
      name: "Aanya Krishnan",
      title: "Director of IT",
      role: "it",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "Two weeks ago",
      summary: "Confirmed integration paths for both reporting and reconciliation surfaces.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "quanta-frontline",
      name: "Karen Whittaker",
      title: "Operations Supervisor",
      role: "frontline",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "Two weeks ago",
      summary: "Day-of work pattern grounded several findings.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "quanta-qa",
      name: "Roberto Aguilera",
      title: "QA Manager",
      role: "operations",
      status: "completed",
      completionPercent: 100,
      responseQuality: "adequate",
      lastActivity: "Two weeks ago",
      summary: "QA review process has bounded rules and clear exception handling.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "quanta-cs",
      name: "Yuki Nakamura",
      title: "Customer Success Lead",
      role: "customer-success",
      status: "completed",
      completionPercent: 100,
      responseQuality: "adequate",
      lastActivity: "Two weeks ago",
      summary: "Renewal motion depends on consistent reporting back to clients.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
  ],
  roleCoverage: [
    {
      role: "executive",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "COO is the named sponsor.",
    },
    {
      role: "operations",
      required: true,
      status: "covered",
      stakeholderCount: 3,
      coverageNote: "VP Operations, QA Manager, and Operations Supervisor.",
    },
    {
      role: "sales",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Sales Director engaged.",
    },
    {
      role: "marketing",
      required: false,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Marketing Director engaged.",
    },
    {
      role: "it",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Director of IT engaged.",
    },
    {
      role: "frontline",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Operations Supervisor engaged.",
    },
    {
      role: "finance",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Finance Director engaged.",
    },
    {
      role: "customer-success",
      required: false,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Customer Success Lead engaged.",
    },
  ],
  supportingInputs: [
    {
      id: "quanta-doc-ops",
      title: "Operations process map (current state)",
      type: "process-map",
      source: "Elena Vargas · VP Operations",
      status: "reviewed",
      evidenceQuality: "strong",
      linkedRole: "operations",
      summary: "Detailed end-to-end ops workflow, anchored most findings.",
    },
    {
      id: "quanta-doc-handoff",
      title: "Sales-to-operations handoff data export",
      type: "data-export",
      source: "Ben Asare · Sales Director",
      status: "reviewed",
      evidenceQuality: "strong",
      linkedRole: "sales",
      summary:
        "Two quarters of sales-to-ops tickets with status and time-in-stage.",
    },
  ],
  followUps: [],
  intakeRiskNotes: [
    "Intake is complete. Outstanding work is in the report stage.",
  ],
};

const CALDERA: IntakeRecord = {
  engagementId: "caldera-aios-q1",
  stakeholders: [
    {
      id: "caldera-leah",
      name: "Leah Ostrander",
      title: "Managing Director",
      role: "executive",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "Three weeks ago",
      summary: "Sponsored the engagement; preferred Workflow System tier early on.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "caldera-jp",
      name: "JP Mendel",
      title: "Head of Operations",
      role: "operations",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "Three weeks ago",
      summary: "Walked through every stage of the deal-to-portfolio pipeline.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "caldera-sara",
      name: "Sara Mehta",
      title: "Compliance Officer",
      role: "operations",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "Three weeks ago",
      summary: "Compliance posture must be reflected in the SOW assumptions.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [
        "Compliance must be reflected in SOW assumptions.",
      ],
    },
    {
      id: "caldera-rico",
      name: "Rico Patel",
      title: "Risk Lead",
      role: "operations",
      status: "completed",
      completionPercent: 100,
      responseQuality: "adequate",
      lastActivity: "Three weeks ago",
      summary: "Risk review pairs naturally with the compliance read.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "caldera-it",
      name: "Ines Karim",
      title: "Director of IT",
      role: "it",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "Three weeks ago",
      summary: "Confirmed integration paths and access controls.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "caldera-frontline",
      name: "Vince Calhoun",
      title: "Senior Analyst",
      role: "frontline",
      status: "completed",
      completionPercent: 100,
      responseQuality: "strong",
      lastActivity: "Three weeks ago",
      summary: "Day-of work patterns; grounded the recommendations.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "caldera-finance",
      name: "Mira Caldwell",
      title: "Finance Director",
      role: "finance",
      status: "completed",
      completionPercent: 100,
      responseQuality: "adequate",
      lastActivity: "Three weeks ago",
      summary: "Confirmed the investment band and timing.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
    {
      id: "caldera-cs",
      name: "Talia Burrows",
      title: "Client Service Lead",
      role: "customer-success",
      status: "completed",
      completionPercent: 100,
      responseQuality: "adequate",
      lastActivity: "Three weeks ago",
      summary: "Renewal and expansion motion is a strong second-engagement signal.",
      keySignals: [],
      openQuestions: [],
      riskFlags: [],
    },
  ],
  roleCoverage: [
    {
      role: "executive",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Managing Director sponsored.",
    },
    {
      role: "operations",
      required: true,
      status: "covered",
      stakeholderCount: 3,
      coverageNote: "Operations + Compliance + Risk all engaged.",
    },
    {
      role: "it",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Director of IT engaged.",
    },
    {
      role: "finance",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Finance Director engaged.",
    },
    {
      role: "frontline",
      required: true,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Senior Analyst engaged.",
    },
    {
      role: "customer-success",
      required: false,
      status: "covered",
      stakeholderCount: 1,
      coverageNote: "Client Service Lead engaged.",
    },
  ],
  supportingInputs: [
    {
      id: "caldera-doc-pipeline",
      title: "Deal-to-portfolio pipeline map",
      type: "process-map",
      source: "JP Mendel · Operations",
      status: "reviewed",
      evidenceQuality: "strong",
      linkedRole: "operations",
      summary: "Anchored the AI Workflow System recommendation.",
    },
    {
      id: "caldera-doc-comp",
      title: "Compliance review checklist",
      type: "policy-doc",
      source: "Sara Mehta · Compliance Officer",
      status: "reviewed",
      evidenceQuality: "strong",
      linkedRole: "operations",
      summary: "Used to scope the governance sections of the report.",
    },
  ],
  followUps: [],
  intakeRiskNotes: [
    "Engagement is past intake. Review compliance footprint before sending the proposal.",
  ],
};

const RECORDS: Record<string, IntakeRecord> = {
  [HELIO.engagementId]: HELIO,
  [MERIDIAN.engagementId]: MERIDIAN,
  [ATLAS.engagementId]: ATLAS,
  [QUANTA.engagementId]: QUANTA,
  [CALDERA.engagementId]: CALDERA,
};

export function getIntakeForEngagement(
  engagementId: string,
): IntakeRecord | undefined {
  return RECORDS[engagementId];
}
