-- SLATE — Phase 1B Proposal/SOW Delivery Sprint P4
-- Operator-only proposal share tokens.
--
-- Per docs/24_PHASE_1B_PROPOSAL_SOW_DELIVERY_CANON.md:
--   - Each row maps a hashed token to exactly one proposal_delivery_snapshots
--     row. The raw token is generated by the application layer, handed back
--     to the operator exactly once, and never persisted — this table
--     stores only `sha256(rawToken)`.
--   - This table does not enable public access by itself. The public
--     `/p/[token]` route is a future Sprint P5 concern; it must look
--     up tokens via a privileged server path, not anonymous Supabase.
--   - First Sprint P4 implementation never emits the raw token to
--     anyone besides the operator who generated it. No email send, no
--     CRM push, no SLATE-mediated delivery.
--   - All locked client-delivery controls (`Prepare Client Review`,
--     `Prepare SOW Draft`, `Send to Client`, `Prepare Report`,
--     `Export Report` on mock paths) remain locked.
--   - Group-B exhibits remain excluded from every snapshot that
--     becomes share-eligible — enforced by the eligibility evaluator
--     in `lib/proposals/share-token-eligibility.ts`, NOT by this DDL.
--   - Only proposal candidate snapshots with `approval_state='approved'`
--     are share-eligible — also enforced in the eligibility evaluator.
--
-- Boundary:
--   - Workspace-scoped via the existing operator-full RLS pattern
--     shared by ai_synthesis_runs / activity_events /
--     report_delivery_snapshots / report_share_tokens /
--     proposal_delivery_snapshots.
--   - No anon policy. No public read.
--   - Service-role inserts only from server actions; the public-route
--     handler in Sprint P5 will read via the operator/service client
--     path canonized then.
--
-- Rollback path (manual):
--   drop table if exists public.proposal_share_tokens cascade;
--
-- Idempotent: safe to re-run.

create extension if not exists pgcrypto;

-- -----------------------------------------------------------------------------
-- proposal_share_tokens
-- -----------------------------------------------------------------------------

create table if not exists public.proposal_share_tokens (
  id                            uuid primary key default gen_random_uuid(),
  workspace_id                  uuid not null references public.workspaces(id) on delete cascade,
  engagement_id                 uuid not null references public.engagements(id) on delete cascade,
  proposal_id                   uuid not null references public.proposals(id) on delete cascade,
  snapshot_id                   uuid not null references public.proposal_delivery_snapshots(id) on delete cascade,

  token_hash                    text not null,
  status                        text not null default 'active'
    check (status in ('active','revoked','expired')),

  audience_label                text,
  recipient_email_hash          text,

  expires_at                    timestamptz not null,
  created_by                    uuid references auth.users(id) on delete set null,
  created_by_label              text,
  created_at                    timestamptz not null default now(),

  revoked_at                    timestamptz,
  revoked_by                    uuid references auth.users(id) on delete set null,
  revoke_reason                 text,

  last_accessed_at              timestamptz,
  access_count                  integer not null default 0,

  metadata                      jsonb not null default '{}'::jsonb,
  updated_at                    timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Constraints
-- -----------------------------------------------------------------------------
-- DO-block guarded `add constraint` so the migration stays idempotent.

do $$
begin
  -- expires_at strictly after created_at; rejects zero-duration tokens
  -- and protects against accidental clock skew at insert time.
  if not exists (
    select 1
    from pg_constraint
    where conname = 'proposal_share_tokens_expires_after_created_check'
      and conrelid = 'public.proposal_share_tokens'::regclass
  ) then
    alter table public.proposal_share_tokens
      add constraint proposal_share_tokens_expires_after_created_check
      check (expires_at > created_at);
  end if;

  -- recipient_email_hash, if populated, must look like a SHA-256 hex
  -- (64 lowercase hex chars). Application layer is responsible for the
  -- actual hashing; this CHECK is a defense-in-depth that catches any
  -- accidental raw-email persistence (raw emails contain `@`, which
  -- this pattern rejects).
  if not exists (
    select 1
    from pg_constraint
    where conname = 'proposal_share_tokens_recipient_email_hash_shape_check'
      and conrelid = 'public.proposal_share_tokens'::regclass
  ) then
    alter table public.proposal_share_tokens
      add constraint proposal_share_tokens_recipient_email_hash_shape_check
      check (
        recipient_email_hash is null
        or recipient_email_hash ~ '^[a-f0-9]{64}$'
      );
  end if;

  -- token_hash must be a SHA-256 hex (same shape rule). Catches the
  -- worst-case bug where someone accidentally stored the raw token
  -- string in this column.
  if not exists (
    select 1
    from pg_constraint
    where conname = 'proposal_share_tokens_token_hash_shape_check'
      and conrelid = 'public.proposal_share_tokens'::regclass
  ) then
    alter table public.proposal_share_tokens
      add constraint proposal_share_tokens_token_hash_shape_check
      check (token_hash ~ '^[a-f0-9]{64}$');
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

create unique index if not exists proposal_share_tokens_token_hash_idx
  on public.proposal_share_tokens (token_hash);

create index if not exists proposal_share_tokens_workspace_idx
  on public.proposal_share_tokens (workspace_id);

create index if not exists proposal_share_tokens_engagement_idx
  on public.proposal_share_tokens (engagement_id);

create index if not exists proposal_share_tokens_proposal_idx
  on public.proposal_share_tokens (proposal_id);

create index if not exists proposal_share_tokens_snapshot_idx
  on public.proposal_share_tokens (snapshot_id);

create index if not exists proposal_share_tokens_status_expires_idx
  on public.proposal_share_tokens (status, expires_at);

-- -----------------------------------------------------------------------------
-- Trigger — keep updated_at fresh
-- -----------------------------------------------------------------------------

create or replace function public.proposal_share_tokens_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists proposal_share_tokens_set_updated_at_trg
  on public.proposal_share_tokens;

create trigger proposal_share_tokens_set_updated_at_trg
  before update on public.proposal_share_tokens
  for each row
  execute function public.proposal_share_tokens_set_updated_at();

-- -----------------------------------------------------------------------------
-- RLS — operator-full only
-- -----------------------------------------------------------------------------

alter table public.proposal_share_tokens enable row level security;

drop policy if exists proposal_share_tokens_operator_full
  on public.proposal_share_tokens;

create policy proposal_share_tokens_operator_full
  on public.proposal_share_tokens
  for all
  to authenticated
  using (workspace_id = (select id from public.workspaces limit 1))
  with check (workspace_id = (select id from public.workspaces limit 1));
