-- SLATE — Phase 1B SOW Share Route Sprint P7-B
-- Operator-only SOW Draft share tokens.
--
-- Per docs/65_PHASE_1B_SOW_SHARE_REELIGIBILITY_CANON.md (which amends
-- docs/28_PHASE_1B_SOW_SHARE_ROUTE_DECISION_CANON.md § 3):
--   - Each row maps a hashed token to exactly one
--     proposal_delivery_snapshots row whose delivery_surface is
--     'sow_draft_candidate'. The raw token is generated by the
--     application layer, handed to the operator exactly once, and never
--     persisted — this table stores only sha256(rawToken).
--   - SEPARATE table from proposal_share_tokens (docs/28 § 3): the SOW
--     lane carries the highest legal weight, and the separation lets an
--     operator/auditor point at a single table and say "these are SOW
--     share artifacts." No share_surface column on the proposal table.
--   - audience_label is NOT NULL (docs/28 § 7 / docs/65): unlike the
--     report/proposal lanes where it is optional, the SOW lane requires
--     it — a SOW share link in the wild without an attached audience is
--     operationally indistinguishable from a leak. The label is
--     operator-visible only; it never renders on the public surface.
--   - source_proposal_snapshot_id is denormalised here for the
--     source-proposal-void cascade (docs/28 § 8): voiding the source
--     Proposal Candidate must cascade-revoke its descendant SOW tokens.
--   - This table does not enable public access by itself. The public
--     `/s/[token]` route looks tokens up via a privileged server path,
--     not anonymous Supabase.
--   - Share eligibility (SOW approval_state='approved', source proposal
--     approved, commercial guard passed, freshness window) is enforced
--     by lib/proposals/sow-share-eligibility.ts, NOT by this DDL.
--   - No signatory identity is ever collected (docs/28 § 7): there is no
--     column for it here by design.
--
-- Boundary:
--   - Workspace-scoped via the same operator-full RLS pattern as
--     proposal_share_tokens. No anon policy. No public read.
--   - Service-role inserts only from server actions; the public-route
--     handler reads via the operator/service client path.
--
-- Rollback path (manual):
--   drop table if exists public.sow_share_tokens cascade;
--
-- Idempotent: safe to re-run.

create extension if not exists pgcrypto;

-- -----------------------------------------------------------------------------
-- sow_share_tokens
-- -----------------------------------------------------------------------------

create table if not exists public.sow_share_tokens (
  id                            uuid primary key default gen_random_uuid(),
  workspace_id                  uuid not null references public.workspaces(id) on delete cascade,
  engagement_id                 uuid not null references public.engagements(id) on delete cascade,
  proposal_id                   uuid not null references public.proposals(id) on delete cascade,
  snapshot_id                   uuid not null references public.proposal_delivery_snapshots(id) on delete cascade,

  -- Denormalised source Proposal Candidate snapshot id, for the
  -- source-proposal-void cascade (docs/28 § 8). Points at the
  -- proposal_delivery_snapshots row (delivery_surface =
  -- 'client_proposal_candidate') the SOW Draft was derived from. Nullable
  -- + on delete set null: proposal snapshots are voided (not deleted), so
  -- the cascade is driven by void, not by row deletion; a stray delete
  -- must never cascade-delete the SOW token, which points at its own
  -- snapshot_id.
  source_proposal_snapshot_id   uuid references public.proposal_delivery_snapshots(id) on delete set null,

  token_hash                    text not null,
  status                        text not null default 'active'
    check (status in ('active','revoked','expired')),

  -- Mandatory on the SOW lane (docs/28 § 7). The mint action rejects an
  -- empty label; this NOT NULL is defense-in-depth at the DB boundary.
  audience_label                text not null,
  recipient_email_hash          text,

  expires_at                    timestamptz not null,
  created_by                    uuid references auth.users(id) on delete set null,
  created_by_label              text,
  created_at                    timestamptz not null default now(),

  revoked_at                    timestamptz,
  revoked_by                    uuid references auth.users(id) on delete set null,
  revoke_reason                 text,

  last_accessed_at              timestamptz,
  access_count                  integer not null default 0,

  metadata                      jsonb not null default '{}'::jsonb,
  updated_at                    timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Constraints
-- -----------------------------------------------------------------------------
-- DO-block guarded `add constraint` so the migration stays idempotent.

do $$
begin
  -- expires_at strictly after created_at; rejects zero-duration tokens
  -- and protects against accidental clock skew at insert time.
  if not exists (
    select 1
    from pg_constraint
    where conname = 'sow_share_tokens_expires_after_created_check'
      and conrelid = 'public.sow_share_tokens'::regclass
  ) then
    alter table public.sow_share_tokens
      add constraint sow_share_tokens_expires_after_created_check
      check (expires_at > created_at);
  end if;

  -- recipient_email_hash, if populated, must look like a SHA-256 hex
  -- (64 lowercase hex chars). Application layer does the hashing; this
  -- CHECK catches any accidental raw-email persistence (raw emails
  -- contain `@`, which this pattern rejects).
  if not exists (
    select 1
    from pg_constraint
    where conname = 'sow_share_tokens_recipient_email_hash_shape_check'
      and conrelid = 'public.sow_share_tokens'::regclass
  ) then
    alter table public.sow_share_tokens
      add constraint sow_share_tokens_recipient_email_hash_shape_check
      check (
        recipient_email_hash is null
        or recipient_email_hash ~ '^[a-f0-9]{64}$'
      );
  end if;

  -- token_hash must be a SHA-256 hex (same shape rule). Catches the
  -- worst-case bug where someone accidentally stored the raw token
  -- string in this column.
  if not exists (
    select 1
    from pg_constraint
    where conname = 'sow_share_tokens_token_hash_shape_check'
      and conrelid = 'public.sow_share_tokens'::regclass
  ) then
    alter table public.sow_share_tokens
      add constraint sow_share_tokens_token_hash_shape_check
      check (token_hash ~ '^[a-f0-9]{64}$');
  end if;

  -- audience_label must be non-empty once trimmed (docs/28 § 7 mandatory
  -- audience). NOT NULL alone would still allow an empty string.
  if not exists (
    select 1
    from pg_constraint
    where conname = 'sow_share_tokens_audience_label_nonempty_check'
      and conrelid = 'public.sow_share_tokens'::regclass
  ) then
    alter table public.sow_share_tokens
      add constraint sow_share_tokens_audience_label_nonempty_check
      check (length(btrim(audience_label)) > 0);
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

create unique index if not exists sow_share_tokens_token_hash_idx
  on public.sow_share_tokens (token_hash);

create index if not exists sow_share_tokens_workspace_idx
  on public.sow_share_tokens (workspace_id);

create index if not exists sow_share_tokens_engagement_idx
  on public.sow_share_tokens (engagement_id);

create index if not exists sow_share_tokens_proposal_idx
  on public.sow_share_tokens (proposal_id);

create index if not exists sow_share_tokens_snapshot_idx
  on public.sow_share_tokens (snapshot_id);

-- Drives the source-proposal-void cascade lookup (docs/28 § 8).
create index if not exists sow_share_tokens_source_proposal_snapshot_idx
  on public.sow_share_tokens (source_proposal_snapshot_id);

create index if not exists sow_share_tokens_status_expires_idx
  on public.sow_share_tokens (status, expires_at);

-- -----------------------------------------------------------------------------
-- Trigger — keep updated_at fresh
-- -----------------------------------------------------------------------------

create or replace function public.sow_share_tokens_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists sow_share_tokens_set_updated_at_trg
  on public.sow_share_tokens;

create trigger sow_share_tokens_set_updated_at_trg
  before update on public.sow_share_tokens
  for each row
  execute function public.sow_share_tokens_set_updated_at();

-- -----------------------------------------------------------------------------
-- RLS — operator-full only
-- -----------------------------------------------------------------------------

alter table public.sow_share_tokens enable row level security;

drop policy if exists sow_share_tokens_operator_full
  on public.sow_share_tokens;

create policy sow_share_tokens_operator_full
  on public.sow_share_tokens
  for all
  to authenticated
  using (workspace_id = (select id from public.workspaces limit 1))
  with check (workspace_id = (select id from public.workspaces limit 1));
